version: "3"

services:
  web:
    container_name: 'apache'
    build: '~/Docker/phpLp2/apache/apacheDocker'
    restart: 'always'
    depends_on:
      - mariadb
      - php
    ports:
      - '8080:80'
    links:
      - mariadb
    volumes:
      - ~/Docker/phpLp2/php:/usr/local/apache2/htdocs
      - ~/Docker/phpLp2/php:/var/www/html
    networks:
      - backend
      - frontend
  php:
    build: '~/Docker/phpLp2/php/phpDocker'
    depends_on:
      - mariadb
    volumes:
      - ~/Docker/phpLp2/php:/var/www/html
      - ~/Docker/phpLp2/php:/usr/local/apache2/htdocs
    ports:
      - '9000:80'
    networks:
      - backend
  mariadb:
    image: mariadb:10.5
    restart: 'always'
    volumes: 
      - /var/lib/mysql/data
      - /var/lib/mysql/logs
      - ~/Docker/phpLp2/mariadb/conf:/etc/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hospital
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
  phpmyadmin:
    image: phpmyadmin
    restart: 'always'
    ports:
      - 8180:80
    environment:
      PMA_HOST: mariadb
      PMA_PASSWORD: senha
    networks:
      - backend
volumes:
  mariadb:
networks:
  backend:
  frontend: