version: "3"

services:
  web:
    image: httpd:latest
    restart: 'always'
    depends_on:
      - mariadb
    ports:
      - '8080:80'
    links:
      - mariadb
  php:
    image: php:7.2-fpm
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    restart: 'always'
    volumes: 
      - /var/lib/mysql/data
      - /var/lib/mysql/logs
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hospital
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
  phpmyadmin:
    image: phpmyadmin
    restart: 'always'
    ports:
      - 8180:80
    environment:
      PMA_HOST: mariadb
      PMA_PASSWORD: senha
volumes:
  mariadb: